
//j'essaie de faire une fonction qui va retourner le nombre de fois que le nombre
try {
    // une fonction inexistante
    zkrngpzkrgpkz();
} catch (error) {
    // j'attrape l'erreur et je la traite comme bon me semble
    console.log(error);
} finally {
    //Action qui sera execut√© a chaque fois qu'il y est une erreur ou non
    alert("Fin de la fonction");
}